config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments, only: [:create, :destroy]
  resources :ideas

  root 'ideas#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :user_name, :body, presence: true
  belongs_to :idea
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  mount_uploader :picture, PictureUploader

  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exceptioe
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:destroy]

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to idea_path(@comment.idea_id)
    else
      redirect_to idea_path(@comment.idea_id), alert: "Error"
    end
  end

  def destroy
    @idea_id = @comment.idea_id
    @comment.destroy
    redirect_to idea_path(@comment.idea_id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :idea_id)
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :set_comment, only: [:show, :edit, :update]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    def set_comment
      @comment = @idea.comments.build
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/comments/_form.html.haml
= form_for @comment, :html => { :class => 'form-horizontal' } do |f|
  .form-group
    = f.label :user_name, :class => 'control-label col-sm-2'
    .col-sm-4= f.text_field :user_name, :class => 'form-control'
  .form-group
    = f.label :body, :class => 'control-label col-sm-2'
    .col-sm-8= f.text_area :body, :class => 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-6
      = f.hidden_field :idea_id, :class => 'form-control'
      = f.submit nil, :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), comments_path, :class => 'btn btn-default'

app/views/comments/edit.html.haml
- model_class = Comment
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/comments/index.html.haml
- model_class = Comment
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:user_name)
      %th= model_class.human_attribute_name(:body)
      %th= model_class.human_attribute_name(:idea_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @comments.each do |comment|
      %tr
        %td= link_to comment.id, comment_path(comment)
        %td= comment.user_name
        %td= comment.body
        %td= comment.idea_id
        %td=l comment.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_comment_path(comment), :class => 'btn btn-primary btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), comment_path(comment), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger btn-xs'

= link_to t('.new', :default => t("helpers.links.new")), new_comment_path, :class => 'btn btn-primary'

app/views/comments/new.html.haml
- model_class = Comment
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/comments/show.html.haml
- model_class = Comment
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:user_name) + ':'
  %br
  = @comment.user_name
%p
  %strong= model_class.human_attribute_name(:body) + ':'
  %br
  = @comment.body
%p
  %strong= model_class.human_attribute_name(:idea_id) + ':'
  %br
  = @comment.idea_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), comments_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_comment_path(@comment), :class => 'btn btn-primary'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), comment_path(@comment), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/ideas/_form.html.haml
= form_for @idea, :html => { :class => 'form-horizontal' } do |f|
  .form-group
    = f.label :name, :class => 'control-label'
    = f.text_field :name, :class => 'form-control'
  .form-group
    = f.label :description, :class => 'control-label'
    = f.text_area :description, :class => 'form-control'
  .form-group
    = f.label :picture, :class => 'control-label'
    = f.file_field :picture, :class => 'filestyle'
  .form-group
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), ideas_path, :class => 'btn btn-default'

app/views/ideas/edit.html.haml
- model_class = Idea
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/ideas/index.html.haml
- model_class = Idea
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:picture)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @ideas.each do |idea|
      %tr
        %td.text-right= link_to idea.id, idea_path(idea)
        %td= idea.name
        %td= idea.description
        %td.text-center= image_tag(idea.picture_url(:thumb)) if idea.picture?
        %td.text-center= idea.created_at.to_s(:db)
        %td.text-center
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_idea_path(idea), :class => 'btn btn-primary btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), idea_path(idea), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger btn-xs'

= link_to t('.new', :default => t("helpers.links.new")), new_idea_path, :class => 'btn btn-primary'

app/views/ideas/new.html.haml
- model_class = Idea
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/ideas/show.html.haml
- model_class = Idea
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @idea.name
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @idea.description
%p
  %strong= model_class.human_attribute_name(:picture) + ':'
  %br
  = image_tag(@idea.picture_url, width: 600) if @idea.picture.present?

%h3 Comments
%table.table.table-striped.table-condenced
  %tbody
    - @idea.comments.all.each do |comment|
      %tr
        %td
          %strong= comment.user_name
          %br
          %p= comment.body
          %p
            = link_to 'Delete', comment_path(comment), method: :delete,
              data: { confirm: '削除してもよろしいですか？' }

= render 'comments/form'

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), ideas_path, :class => 'btn'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Rails Girls
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render "shared/header"

    - if notice
      .alert.alert-warning= notice
    - if alert
      .alert.alert-danger= alert

    .container
      = yield
    = render "shared/footer"

app/views/shared/_footer.html.haml
%footer.footer
  .container-fluid.text-right.text-muted Rails Girl 2015

app/views/shared/_header.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{ "data-toggle": :collapse,
        "data-target": "#bs-nabvar", "aria-expanded": false }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "The Idea app", root_path, class: "navbar-brand"
    #bs-navbar.collapse.navbar-collapse
      %p.navbar-text.pull-right
        - if user_signed_in?
          Logged in as
          %string= "#{current_user.email} ."
          = link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link'
          |
          = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'navbar-link'
        - else
          = link_to 'Sign up', new_user_registration_path, class: 'navbar-link'
          |
          = link_to 'Login', new_user_session_path, class: 'navbar-link'

      %ul.nav.navbar-nav
        %li.active
          = link_to "Idea", ideas_path